### ISSUE TITLE
Move recipes names from namespace to URL

### ISSUE THREAD

**Issue by yohanboniface** [etalab/utilery#3]
So instead of `http://tile.org/recipe1:layername/0/0/0.png` we'd have `http://tile.org/recipe1/layername/0/0/0.png`.
We'd keep the recipe name optional in the URL, and then no recipe name would means `default` one.

Cons:
- for the consumers, one HTTP call will be needed per recipe (but we can see a recipe as a source, and that doesn't matter at the end that two sources are served by the same piece of code or not, from the consumer point of view)

Pros:
- makes the API much simpler (what is Utilery supposed to answer with an URL like `http://tile.org/all+default:all+roads+tgi:xxx+defaults:buildings/0/0/0.png` ? Valid request? Invalid? Serve all? serve given layer names?)
- less URL possibilities means easier to cache

My opinion is that recipes as namespaces doesn't match the simplicity mantra of this project.

@cquest thoughts?

**Comment by cquest** [comment]
ok with the change...
